/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../src/seed.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from 'ng4-click-outside/lib/click-outside.module';
import * as import6 from '@angular/common/src/localization';
import * as import7 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import8 from '@angular/core/src/di/injector';
import * as import9 from '@angular/core/src/i18n/tokens';
import * as import10 from '../../src/seed.service';
class SeedModuleInjector extends import0.NgModuleInjector<import1.SeedModule> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _ClickOutsideModule_3:import5.ClickOutsideModule;
  _SeedModule_4:import1.SeedModule;
  __NgLocalization_5:import6.NgLocaleLocalization;
  __RadioControlRegistry_6:import7.RadioControlRegistry;
  __SeedService_7:any;
  constructor(parent:import8.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_5():import6.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import6.NgLocaleLocalization(this.parent.get(import9.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _RadioControlRegistry_6():import7.RadioControlRegistry {
    if ((this.__RadioControlRegistry_6 == null)) { (this.__RadioControlRegistry_6 = new import7.RadioControlRegistry()); }
    return this.__RadioControlRegistry_6;
  }
  get _SeedService_7():any {
    if ((this.__SeedService_7 == null)) { (this.__SeedService_7 = import1.seedServiceFactory()); }
    return this.__SeedService_7;
  }
  createInternal():import1.SeedModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._ClickOutsideModule_3 = new import5.ClickOutsideModule();
    this._SeedModule_4 = new import1.SeedModule();
    return this._SeedModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.ClickOutsideModule)) { return this._ClickOutsideModule_3; }
    if ((token === import1.SeedModule)) { return this._SeedModule_4; }
    if ((token === import6.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import7.RadioControlRegistry)) { return this._RadioControlRegistry_6; }
    if ((token === import10.SeedService)) { return this._SeedService_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SeedModuleNgFactory:import0.NgModuleFactory<import1.SeedModule> = new import0.NgModuleFactory(SeedModuleInjector,import1.SeedModule);